#-------------------------------------------------------------------------#
#
#SWE3005_42 Introduction of Computer Architecture(Spring 2021)
#
#Instructor :Prof.Tae Hee Han(than@skku.edu)
#
#Editor: Shim jae Eun(david4466@g.skku.com), Key Heon Lee (aemincrest@g.skku.edu)
#
#Description : Binary Search in RISC-V
#
#Copyright(C) 2021 SungKyunKwan University
#
#-------------------------------------------------------------------------#

.section .text
.globl binary_search




#------------------------------------------------------------
#                       binary_search function
#------------------------------------------------------------



#---------------------------------------------------------------------------
#	you can write your code here: START
#---------------------------------------------------------------------------

binary_search:








#---------------------------------------------------------------------------
#	you can write your code here: END
#---------------------------------------------------------------------------