/* 
**    WARNING : DO NOT EDIT THIS FILE!
**    ALL CHANGES ON THIS FILE WILL BE DISCARDED!
*/
#include <stdio.h>

#define BUF_LEN 1024
#define VAR_COUNT 5

#define NO_SWAP -1

typedef enum swap_type
{
    VALUE = 0,
    PTR = 1
} swap_type_t;

void swap(int** var_pp, int i_a, int i_b, int is_swap_ptr);
void print_arr(char* title, int i_a, int i_b, int* var_p, int** var_pp);





// execute swap()
void swap_wrapper(int* var_p, int** var_pp, int i_a, int i_b, swap_type_t st)
{
    swap(var_pp, i_a, i_b, (int) st);
    
    print_arr( (st == VALUE ? "Swap Value" : "Swap Pointer"),
	       i_a, i_b, var_p, var_pp );
}





int main(int argc, char* argv[])
{
    int var[VAR_COUNT],
	* var_p[VAR_COUNT];
    
    // init vars
    for (int i = 0; i < VAR_COUNT; i++)
    {
	var[i] = i*10;
	var_p[i] = &var[i];
    }


    
    print_arr("\nInitial state", NO_SWAP, NO_SWAP, var, var_p);
    
    swap_wrapper(var, var_p, 0, 1, PTR);
    swap_wrapper(var, var_p, 0, 1, VALUE);
    swap_wrapper(var, var_p, 2, 4, PTR);
    swap_wrapper(var, var_p, 3, 0, PTR);
    swap_wrapper(var, var_p, 2, 3, VALUE);
    swap_wrapper(var, var_p, 0, 1, VALUE);
    
    return 0;
}

// print all members of var & var_p
void print_arr(char* title, int i_a, int i_b, int* var_p, int** var_pp)
{
    if ( ! (i_a == NO_SWAP || i_b == NO_SWAP) )
	printf("%s:\t%d <=> %d\n\t", title, i_a, i_b);
    else
	printf("%s\n\t", title);
    
    for (int i = 0; i < VAR_COUNT; i++)
	printf("%s[%d]\x1B[0m\t",
	       (i==i_a || i==i_b ? "\x1B[32m" : ""), i);
    
    printf("\n[var]\t");
    for (int i = 0; i < VAR_COUNT; i++)
	printf("%d\t", var_p[i]);
    
    printf("\n[ptr]\t");
    for (int i = 0; i < VAR_COUNT; i++)
	printf("%d\t", *(var_pp[i]));
    
    printf("\n\n");
}
